### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Analytics"

### ISSUE THREAD

**Issue by isonlaxman** [segmentio/analytics-react-native#252]
I recently upgraded my @react-native-firebase/app and @react-native-firebase/messaging to 10.4.0, and since then I've not been able to do 'pod install'. I've removed pods, podfile.lock, and also done pod update. I'm stuck with this error:

```
[!] CocoaPods could not find compatible versions for pod "Analytics":
  In Podfile:
    RNAnalytics (from `../node_modules/@segment/analytics-react-native`) was resolved to 1.3.2, which depends on
      Analytics (~> 4.1)

    RNAnalyticsIntegration-Firebase (from `../node_modules/@segment/analytics-react-native-firebase`) was resolved to 1.3.2, which depends on
      Analytics

    RNAnalyticsIntegration-Firebase (from `../node_modules/@segment/analytics-react-native-firebase`) was resolved to 1.3.2, which depends on
      Segment-Firebase was resolved to 2.4.1, which depends on
        Analytics (~> 3.2)

CocoaPods could not find compatible versions for pod "nanopb":
  In Podfile:
    RNAnalyticsIntegration-Firebase (from `../node_modules/@segment/analytics-react-native-firebase`) was resolved to 1.3.2, which depends on
      Segment-Firebase was resolved to 2.7.0, which depends on
        FirebaseAnalytics (~> 6.1) was resolved to 6.1.2, which depends on
          nanopb (~> 0.3)

    RNFBMessaging (from `../node_modules/@react-native-firebase/messaging`) was resolved to 10.4.0, which depends on
      Firebase/Messaging (~> 7.3.0) was resolved to 7.3.0, which depends on
        Firebase/CoreOnly (= 7.3.0) was resolved to 7.3.0, which depends on
          FirebaseCore (= 7.3.0) was resolved to 7.3.0, which depends on
            FirebaseCoreDiagnostics (~> 7.0) was resolved to 7.3.0, which depends on
              nanopb (~> 2.30906.0)
```

Podfile:
```
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'sofy' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  use_unimodules!(modules_paths: ['../node_modules'])


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
```

Package.json:
```
"@segment/analytics-react-native": "^1.3.2",
"@segment/analytics-react-native-firebase": "^1.3.2",
"@react-native-firebase/app": "^10.4.0",
"@react-native-firebase/messaging": "^10.4.0",
```

**Comment by FadiAboMsalam** [comment]
same issue here any fix ?

**Comment by Karthiksheety** [comment]
Same issue i am facing if you guys had fix it please update it here.

Mine Deployment target was 10

Issue says that Specs satisfying the `RNAnalytics (from `../node_modules/@segment/analytics-react-native`)` dependency were found, but they required a higher minimum deployment target.

**Comment by isonlaxman** [comment]
> Issue says that Specs satisfying the `RNAnalytics (from `../node_modules/@segment/analytics-react-native`)` dependency were found, but they required a higher minimum deployment target.

You can fix that issue by just making the deployment target = 11, but then you'll face the issue that I face

**Comment by dgranahan** [comment]
I ran `pod update Analytics` which fixed this issue for me.

**Comment by isonlaxman** [comment]
> I ran `pod update Analytics` which fixed this issue for me.

If I do this I get compatibility issues with Firebase/CoreOnly

**Comment by brayn003** [comment]
`@segment/analytics-react-native` and `@react-native-firebase/app` are creating conflicts because of different versions of the same dependency

**Comment by isonlaxman** [comment]
> `@segment/analytics-react-native` and `@react-native-firebase/app` are creating conflicts because of different versions of the same dependency

yeah, that seems to be the issue, if I satisfy one of them the other complaints.

**Comment by zer0flag** [comment]
Same issue here. You could change the pinned Analytics version in the podfile in the node_modules folder but that's not a good solution 😄 Seems to be we need to wait for an updated version provided by the segment team?

**Comment by DmytroKhutornoi** [comment]
This worked for me:

- in **Podfile** change `platform :ios, '10.0'` to `platform :ios, '11.0'`
- in **project.pbxproj** set all iOS Deployment Targets to 11.0
- update Firebase and Appcenter versions in **package.json**
- delete **Podfile.lock** to renew Firebase dependencies

**Comment by isonlaxman** [comment]
> This worked for me:
> 
> * in **Podfile** change `platform :ios, '10.0'` to `platform :ios, '11.0'`
> * in **project.pbxproj** set all iOS Deployment Targets to 11.0
> * update Firebase and Appcenter versions in **package.json**
> * delete **Podfile.lock** to renew Firebase dependencies

can I know exactly what versions of @react-native-firbease/app, @react-native-firebase/messaging, @segmentio/react-native-firebase, and @segmentio/react-native-firebase-analytics you have? Thanks

**Comment by rodrigocoliveira** [comment]
I am currently stucked on the same issue.

**Comment by brayn003** [comment]
I just removed segment and integrated firebase without it

**Comment by isonlaxman** [comment]
> I just removed segment and integrated firebase without it

that's what I'm thinking of doing right now

**Comment by nsmet** [comment]
We're having the same issue. We downgraded our firebase packages to all releases before they started using the new IOS SDK 7.x. But this is really not ideal as we're getting a ton of warnings from versions not being aligned...

**Comment by ErickMaeda** [comment]
I was able to solve it by just downgrade the platform version required from 11 to 10.

File `node_modules/@segment/analytics-react-native/RNAnalytics.podspec`

Changed 
from `s.platform            = :ios, '11.0'` to from `s.platform            = :ios, '11.0'`

run pod install again, and it's working.

**Comment by bsneed** [comment]
fixed, release coming shortly.

**Comment by FadiAboMsalam** [comment]
@bsneed  when this will be released ?

**Comment by bsneed** [comment]
@FadiAboMsalam running into CI issues atm, but as soon as I'm past that.  hoping for today or tomorrow at the latest.

**Comment by brayn003** [comment]
Is there a way I can help with this?

**Comment by bsneed** [comment]
Not really, but I do appreciate the offer!  Thanks so much!

**Comment by raybotha** [comment]
This actually isn't fixed because `@segment/analytics-react-native-firebase` uses `Segment-Firebase` which depends on `Analytics (~> 3.2)` so the same conflict happens.

**Comment by bsneed** [comment]
@raybotha you should update your pods.  segment-firebase hasn't been pinned for some time now I believe, see here: https://github.com/segment-integrations/analytics-ios-integration-firebase/blob/master/Segment-Firebase.podspec

Use 2.7.0, should work for you.

**Comment by raybotha** [comment]
> @raybotha you should update your pods. segment-firebase hasn't been pinned for some time now I believe, see here: https://github.com/segment-integrations/analytics-ios-integration-firebase/blob/master/Segment-Firebase.podspec
> 
> Use 2.7.0, should work for you.

2.7.0 also conflicts because of its outdated FirebaseAnalytics dependency:
```
  In Podfile:
    RNAnalyticsIntegration-Firebase (from `../node_modules/@segment/analytics-react-native-firebase`) was resolved to 1.4.1, which depends on
      Segment-Firebase was resolved to 2.7.0, which depends on
        FirebaseAnalytics (~> 6.1) was resolved to 6.1.2, which depends on
          nanopb (~> 0.3)

    RNFBMessaging (from `../node_modules/@react-native-firebase/messaging`) was resolved to 10.6.4, which depends on
      Firebase/Messaging (~> 7.5.0) was resolved to 7.5.0, which depends on
        FirebaseMessaging (~> 7.5.0) was resolved to 7.5.0, which depends on
          FirebaseCore (~> 7.0) was resolved to 7.5.0, which depends on
            FirebaseCoreDiagnostics (~> 7.4) was resolved to 7.5.0, which depends on
              nanopb (~> 2.30907.0)```

**Comment by bsneed** [comment]
Hi @raybotha, I did some sleuthing and see this to be a known issue internally.  If you can give me some details as to the impact on your business I can get it added to the internal JIRA ticket and try to get it prioritized with the appropriate team.  Optionally, you can also contact our support department and they can do this for you too in a more private manner.  The internal ticket is `STRATCONN-544`, support should be able to look that up on JIRA and get your info added to it.

**Comment by nsmet** [comment]
Hi we're also still experiencing problems with firebase packages in combination with @segment/analytics-react-native-firebase. We're not getting the pod dependency cycle problems, but other problems rose. 

I'm not able to build my app because of GoogleUtilities when using the segment firebase package. giving the following error: 
```
'GoogleUtilities/GULAppEnvironmentUtil.h' file not found
```

Package.json
```
"@react-native-firebase/app": "^10.8.0",
"@react-native-firebase/auth": "^10.8.0",
"@react-native-firebase/crashlytics": "^10.8.0",
"@react-native-firebase/database": "^10.8.0",
"@react-native-firebase/firestore": "^10.8.0",
"@react-native-firebase/functions": "^10.8.0",
"@react-native-firebase/remote-config": "^10.8.0",
"@segment/analytics-react-native": "^1.4.1",
"@segment/analytics-react-native-branch": "^1.3.2",
"@segment/analytics-react-native-firebase": "^1.4.1",
```

Pod install output
```
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing Analytics (3.9.0)
Installing AppAuth (1.4.0)
Installing BVLinearGradient (2.5.6)
Installing Base64 (1.1.2)
Installing BoringSSL-GRPC (0.0.7)
Installing Branch (0.35.0)
Installing CodePush (7.0.0)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.63.2)
Installing FBReactNativeSpec (0.63.2)
Installing FBSDKCoreKit (8.2.0)
Installing FBSDKLoginKit (8.2.0)
Installing FBSDKShareKit (8.2.0)
Installing Firebase (3.3.0)
Installing Firebase (7.6.0)
Installing FirebaseABTesting (7.6.0)
Installing FirebaseAnalytics (3.2.1)
Installing FirebaseAuth (7.6.0)
Installing FirebaseCore (7.6.0)
Installing FirebaseCoreDiagnostics (7.6.0)
Installing FirebaseCrashlytics (7.6.0)
Installing FirebaseDatabase (7.6.0)
Installing FirebaseFirestore (7.6.0)
Installing FirebaseFunctions (7.6.0)
Installing FirebaseInstallations (7.6.0)
Installing FirebaseInstanceID (1.0.9)
Installing FirebaseRemoteConfig (7.6.0)
Installing Folly (2020.01.13.00)
Installing GTMAppAuth (1.1.0)
Installing GTMSessionFetcher (1.5.0)
Installing GoogleDataTransport (8.2.0)
Installing GoogleInterchangeUtilities (1.2.2)
Installing GoogleSignIn (5.0.2)
Installing GoogleSymbolUtilities (1.1.2)
Installing GoogleUtilities (1.3.2)
Installing GoogleUtilities (7.2.2)
Installing Intercom (6.0.2)
Installing JWT (3.0.0-beta.12)
Installing OneSignal (3.1.0)
Installing PromisesObjC (1.2.12)
Installing Purchases (3.9.2)
Installing PurchasesCoreSwift (3.9.2)
Installing PurchasesHybridCommon (1.5.0)
Installing RCTRequired (0.63.2)
Installing RCTTypeSafety (0.63.2)
Installing RNAnalytics (1.4.1)
Installing RNAnalyticsIntegration-Branch (1.3.2)
Installing RNAnalyticsIntegration-Firebase (1.4.1)
Installing RNAppleAuthentication (1.1.2)
Installing RNCAsyncStorage (1.12.1)
Installing RNCMaskedView (0.1.10)
Installing RNCPushNotificationIOS (1.8.0)
Installing RNDateTimePicker (3.0.8)
Installing RNDeviceInfo (5.6.5)
Installing RNFBApp (10.8.0)
Installing RNFBAuth (10.8.0)
Installing RNFBCrashlytics (10.8.0)
Installing RNFBDatabase (10.8.0)
Installing RNFBFirestore (10.8.0)
Installing RNFBFunctions (10.8.0)
Installing RNFBRemoteConfig (10.8.0)
Installing RNGestureHandler (1.9.0)
Installing RNGoogleSignin (4.0.3)
Installing RNKeychain (4.0.5)
Installing RNLocalize (2.0.1)
Installing RNPurchases (4.0.0)
Installing RNReanimated (1.13.2)
Installing RNSVG (12.1.0)
Installing RNScreens (2.16.1)
Installing React (0.63.2)
Installing React-Core (0.63.2)
Installing React-CoreModules (0.63.2)
Installing React-RCTActionSheet (0.63.2)
Installing React-RCTAnimation (0.63.2)
Installing React-RCTBlob (0.63.2)
Installing React-RCTImage (0.63.2)
Installing React-RCTLinking (0.63.2)
Installing React-RCTNetwork (0.63.2)
Installing React-RCTSettings (0.63.2)
Installing React-RCTText (0.63.2)
Installing React-RCTVibration (0.63.2)
Installing React-callinvoker (0.63.2)
Installing React-cxxreact (0.63.2)
Installing React-jsi (0.63.2)
Installing React-jsiexecutor (0.63.2)
Installing React-jsinspector (0.63.2)
Installing ReactCommon (0.63.2)
Installing SSZipArchive (2.2.3)
Installing Segment-Branch (0.1.23)
Installing Segment-Firebase (1.0.0)
Installing Yoga (1.14.0)
Installing abseil (0.20200225.0)
Installing boost-for-react-native (1.63.0)
Installing gRPC-C++ (1.28.2)
Installing gRPC-Core (1.28.2)
Installing glog (0.3.5)
Installing leveldb-library (1.22)
Installing nanopb (2.30907.0)
Installing purse (1.0.0)
Installing react-native-branch (5.0.0)
Installing react-native-config (1.4.0)
Installing react-native-fbsdk (3.0.0)
Installing react-native-in-app-review (2.1.5)
Installing react-native-intercom (14.0.0)
Installing react-native-keep-awake (4.0.0)
Installing react-native-netinfo (4.7.0)
Installing react-native-onesignal (4.0.3)
Installing react-native-safe-area (0.5.1)
Installing react-native-safe-area-context (3.1.9)
Installing react-native-slider (2.0.9)
Installing react-native-splash-screen (3.2.0)
Installing react-native-track-player (1.2.3)
Installing react-native-webview (11.0.2)
Installing rn-fetch-blob (0.10.16)
Generating Pods project
Integrating client project
Pod installation complete! There are 71 dependencies from the Podfile and 114 total pods installed.
```

Conflicting pods. Here it installs older versions of Firebase and GoogleUtilitites and then overrides it with newer versions. 
```
Installing Firebase 3.3.0
Installing Firebase 7.6.0 (was 3.3.0)
Installing GoogleUtilities 1.3.2
Installing GoogleUtilities 7.2.2 (was 1.3.2)
```
Anyone know how this is being caused?

**Comment by bsneed** [comment]
Segment-Firebase is using an out of date version it looks like.  We have a ticket internally and that team is looking into it.

**Comment by zer0flag** [comment]
> Segment-Firebase is using an out of date version it looks like. We have a ticket internally and that team is looking into it.

I'm still running into the same issue regarding the outdated Segment-Firebase version. When do you think this will be fixed @bsneed? I'm thinking of removing segment at all because firebase is essential for us but actually I don't want to do that :)

**Comment by cmlarsen** [comment]
> Segment-Firebase is using an out of date version it looks like. We have a ticket internally and that team is looking into it.

We also need to upgrade Firebase (in prep for iOS 14.5 and the ad attribution changes) but can't until we are able to get Segment to work with it.

**Comment by nsmet** [comment]
we have the same issue with the attribution, we decided to remove this package until we can have it fixed

**Comment by bsneed** [comment]
Just a heads up, since you all reported it so much, STRATCONN-544 ended up getting assigned to me.  Look for an update soon!

**Comment by bsneed** [comment]
Just pushed a new version of Segment-Firebase to CocoaPods.  This should resolve the build problems ya'll were seeing. Changelog here: https://cocoapods.org/pods/Segment-Firebase#changelog

**Comment by zer0flag** [comment]
> Just pushed a new version of Segment-Firebase to CocoaPods. This should resolve the build problems ya'll were seeing. Changelog here: https://cocoapods.org/pods/Segment-Firebase#changelog

Thanks @bsneed! Now it works perfectly! Just 💅 - On the changelog there's a typo on the year:

Version 2.7.1 (5th March, 202**1**)

**Comment by bsneed** [comment]
@zer0flag sweet!  ah crud!  it will live in infamy now. :S

**Comment by alexscarlett** [comment]
@bsneed I'm experiencing the same type of dependency error when attempting to add `@segment/analytics-react-native-firebase` to my project alongside `@react-native-firebase/app` (and many other `@react-native-firebase/*` packages for that matter)

Looks like the packages depend on `Firebase/CoreOnly` `= 5.0.0` and `= 7.4.0` respectively.

For context -- I'm attempting to follow the "Usage" directions [here](https://github.com/segmentio/analytics-react-native#usage) and hoping send analytics events through Segment instead of direct to Firebase since our app is currently sending many other events being consumed by other destinations.

Seems like you fixed this dependency issue in the Pod described above, so wondering if there is a plan to fix the `@segment/analytics-react-native-firebase` as well? 

Sorry to open this thread back up and if this isn't the appropriate place for such a question, but wasn't able to find a repo for that specific library to file an issue.

Thanks in advance for any help/guidance here!

**Comment by faisal-vf** [comment]
`@segment/analytics-react-native-firebase` integration is still not fixed. It resolves to Segment-Firebase `1.0.0`. I get this error when attempting `pod install`

```
[!] CocoaPods could not find compatible versions for pod "Firebase/Core":
  In snapshot (Podfile.lock):
    Firebase/Core (= 7.3.0)

  In Podfile:
    RNAnalyticsIntegration-Firebase (from `../node_modules/@segment/analytics-react-native-firebase`) was resolved to 1.4.3, which depends on
      Segment-Firebase was resolved to 1.0.0, which depends on
        Firebase/Core (~> 3.3.0)

    RNFBAnalytics (from `../node_modules/@react-native-firebase/analytics`) was resolved to 10.4.0, which depends on
      Firebase/Analytics (~> 7.3.0) was resolved to 7.3.0, which depends on
        Firebase/Core (= 7.3.0)
```
Any help/guidance regarding this will be greatly appreciated.

**Comment by Andriiklymiuk** [comment]
Same issue on clean project and latest version of firebase, any help?
"@segment/analytics-react-native": "^1.5.0",
    "@segment/analytics-react-native-firebase": "^1.5.0",
    "@segment/analytics-react-native-mixpanel": "^1.5.0",
    "react": "17.0.2",
    "react-native": "0.65.1",
        "@react-native-firebase/analytics": "^12.7.3",
    "@react-native-firebase/app": "^12.7.3",
    "@react-native-firebase/crashlytics": "^12.7.3",
    "@react-native-firebase/messaging": "^12.7.3",

**Comment by butri71** [comment]
any fix yet?

**Comment by Godzilla912** [comment]
if anyone get this problem.
delete pod lock file with pod folder (remember not pod file)
then install agian pod
"pod install"

**Comment by ajith-acumen** [comment]
i adding firebase auth package then get error

[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    FirebaseCoreDiagnostics (= 1.4.0) was resolved to 1.4.0, which depends on
      GoogleDataTransportCCTSupport (~> 3.1) was resolved to 3.2.0, which depends on
        GoogleDataTransport (~> 6.1)

    google_mlkit_selfie_segmentation (from `.symlinks/plugins/google_mlkit_selfie_segmentation/ios`) was resolved to 0.1.0, which depends on
      GoogleMLKit/SegmentationSelfie (~> 3.1.0) was resolved to 3.1.0, which depends on
        MLKitSegmentationSelfie (~> 1.0.0-beta7) was resolved to 1.0.0-beta7, which depends on
          MLKitSegmentationCommon (= 1.0.0-beta7) was resolved to 1.0.0-beta7, which depends on
            MLKitCommon (~> 7.0) was resolved to 7.0.0, which depends on
              GoogleDataTransport (~> 9.0)

CocoaPods could not find compatible versions for pod "MLKitCommon":
  In Podfile:
    google_mlkit_entity_extraction (from `.symlinks/plugins/google_mlkit_entity_extraction/ios`) was resolved to 0.5.0, which depends on
      GoogleMLKit/EntityExtraction (~> 3.1.0) was resolved to 3.1.0, which depends on
        GoogleMLKit/MLKitCore (= 3.1.0) was resolved to 3.1.0, which depends on
          MLKitCommon (~> 7.0.0)

    google_mlkit_entity_extraction (from `.symlinks/plugins/google_mlkit_entity_extraction/ios`) was resolved to 0.5.0, which depends on
      GoogleMLKit/EntityExtraction (~> 3.1.0) was resolved to 3.1.0, which depends on
        MLKitEntityExtraction (~> 1.0.0-beta8) was resolved to 1.0.0-beta8, which depends on
          MLKitNaturalLanguage (~> 4.1) was resolved to 4.2.0, which depends on
            MLKitCommon (~> 8.0)

    google_mlkit_selfie_segmentation (from `.symlinks/plugins/google_mlkit_selfie_segmentation/ios`) was resolved to 0.1.0, which depends on
      GoogleMLKit/SegmentationSelfie (~> 3.1.0) was resolved to 3.1.0, which depends on
        MLKitSegmentationSelfie (~> 1.0.0-beta7) was resolved to 1.0.0-beta7, which depends on
          MLKitSegmentationCommon (= 1.0.0-beta7) was resolved to 1.0.0-beta7, which depends on
            MLKitCommon (~> 7.0)

CocoaPods could not find compatible versions for pod "MLKitLanguageID":
  In Podfile:
    google_mlkit_language_id (from `.symlinks/plugins/google_mlkit_language_id/ios`) was resolved to 0.4.0, which depends on
      GoogleMLKit/LanguageID (~> 3.1.0) was resolved to 3.1.0, which depends on
        MLKitLanguageID (~> 3.1.0)

    google_mlkit_smart_reply (from `.symlinks/plugins/google_mlkit_smart_reply/ios`) was resolved to 0.4.0, which depends on
      GoogleMLKit/SmartReply (~> 3.1.0) was resolved to 3.1.0, which depends on
        MLKitSmartReply (~> 2.1.0) was resolved to 2.1.0, which depends on
          MLKitLanguageID (~> 3.1)

CocoaPods could not find compatible versions for pod "MLKitTextRecognitionCommon":
  In Podfile:
    google_mlkit_text_recognition (from `.symlinks/plugins/google_mlkit_text_recognition/ios`) was resolved to 0.4.0, which depends on
      GoogleMLKit/TextRecognitionDevanagari (~> 3.1.0) was resolved to 3.1.0, which depends on
        MLKitTextRecognitionDevanagari (~> 1.0.0-beta5) was resolved to 1.0.0-beta5, which depends on
          MLKitTextRecognitionCommon (= 1.0.0-beta5)

    google_mlkit_text_recognition (from `.symlinks/plugins/google_mlkit_text_recognition/ios`) was resolved to 0.4.0, which depends on
      GoogleMLKit/TextRecognitionJapanese (~> 3.1.0) was resolved to 3.1.0, which depends on
        MLKitTextRecognitionJapanese (~> 1.0.0-beta5) was resolved to 1.0.0-beta6, which depends on
          MLKitTextRecognitionCommon (= 1.0.0-beta6)

CocoaPods could not find compatible versions for pod "MLKitVision":
  In Podfile:
    google_mlkit_commons (from `.symlinks/plugins/google_mlkit_commons/ios`) was resolved to 0.2.0, which depends on
      MLKitVision

    google_mlkit_image_labeling (from `.symlinks/plugins/google_mlkit_image_labeling/ios`) was resolved to 0.4.0, which depends on
      GoogleMLKit/ImageLabelingCustom (~> 3.1.0) was resolved to 3.1.0, which depends on
        MLKitImageLabelingCustom (~> 2.1.0) was resolved to 2.1.0, which depends on
          MLKitImageLabelingCommon (~> 4.1) was resolved to 4.2.0, which depends on
            MLKitVision (~> 4.2)

    google_mlkit_selfie_segmentation (from `.symlinks/plugins/google_mlkit_selfie_segmentation/ios`) was resolved to 0.1.0, which depends on
      GoogleMLKit/SegmentationSelfie (~> 3.1.0) was resolved to 3.1.0, which depends on
        MLKitSegmentationSelfie (~> 1.0.0-beta7) was resolved to 1.0.0-beta7, which depends on
          MLKitSegmentationCommon (= 1.0.0-beta7) was resolved to 1.0.0-beta7, which depends on
            MLKitXenoCommon (= 1.0.0-beta9) was resolved to 1.0.0-beta9, which depends on
              MLKitVision (~> 4.1)

CocoaPods could not find compatible versions for pod "MLKitXenoCommon":
  In Podfile:
    google_mlkit_pose_detection (from `.symlinks/plugins/google_mlkit_pose_detection/ios`) was resolved to 0.4.0, which depends on
      GoogleMLKit/PoseDetection (~> 3.1.0) was resolved to 3.1.0, which depends on
        MLKitPoseDetection (~> 1.0.0-beta9) was resolved to 1.0.0-beta10, which depends on
          MLKitXenoCommon (= 1.0.0-beta10)

    google_mlkit_selfie_segmentation (from `.symlinks/plugins/google_mlkit_selfie_segmentation/ios`) was resolved to 0.1.0, which depends on
      GoogleMLKit/SegmentationSelfie (~> 3.1.0) was resolved to 3.1.0, which depends on
        MLKitSegmentationSelfie (~> 1.0.0-beta7) was resolved to 1.0.0-beta7, which depends on
          MLKitSegmentationCommon (= 1.0.0-beta7) was resolved to 1.0.0-beta7, which depends on
            MLKitXenoCommon (= 1.0.0-beta9)

**Comment by Power51214** [comment]
cd ios && then run pod repo update && the run pod install
it will solve the problem
