### ISSUE TITLE
Google play doesn't allow to submit the application - our app includes non-compliant SDK version

### ISSUE THREAD

**Issue by TharinduKetipe** [segmentio/analytics-react-native#614]
Google play rejected app submission saying that  our app includes non-compliant SDK version. They are looking for the android native segmentation library v4.10.1.. But your latest version of the library v2.4.0 is still pointed to the v4.9.3 of the native library.
<img width="666" alt="Screenshot 2022-07-22 at 18 02 11" src="https://user-images.githubusercontent.com/8614553/180440093-c37af3f4-3b59-468a-a83d-7720e8f07c69.png">

- `analytics-react-native` version: 2.4.0
- React Native version: 0.63.4
- Only in android

**Comment by captainCoolMJ** [comment]
I can confirm we're receiving this notice as well, definitely hoping for this to get resolved, thanks!

<img width="601" alt="image" src="https://user-images.githubusercontent.com/1666604/180487717-011fda32-41a8-42fc-a055-23a469ee2abe.png">

**Comment by oscb** [comment]
Which plugins are you using? v2+ doesn't use the native android library anymore. 

What I'm thinking is happening is if you are using some of the old plugins for v1 which still reference `segment-android`, make sure you switch to the v2 plugins, here's a table with the equivalent ones: https://github.com/segmentio/analytics-react-native/blob/master/MIGRATION_GUIDE.md#plugins

If you are still in v1 or any of the plugins you use hasn't been migrated you can upgrade to v1.5.2 which solves this issue.

**Comment by josehernandezv** [comment]
I'm not using any plugins, I migrated to v2 and I'm also facing the same issue

**Comment by gislawill** [comment]
I'm seeing this warning as well and similarly not using any plugins, using v2, and have searched the project's source files for any reference to `segment-android` without success.

**Comment by oscb** [comment]
Can you guys try clearing the gradle cache and doing a clean build? 

I remember some people having this problem when upgrading to 1.5.2 which fixed this issue in v1, it kept the old version of analytics-android around for some reason.

Just to be clear there isn't any reference to analytics-android in v2. So that's why I suspect something leftover in the build.

**Comment by TharinduKetipe** [comment]
> Which plugins are you using? v2+ doesn't use the native android library anymore.
> 
> What I'm thinking is happening is if you are using some of the old plugins for v1 which still reference `segment-android`, make sure you switch to the v2 plugins, here's a table with the equivalent ones: https://github.com/segmentio/analytics-react-native/blob/master/MIGRATION_GUIDE.md#plugins
> 
> If you are still in v1 or any of the plugins you use hasn't been migrated you can upgrade to v1.5.2 which solves this issue.

I'm getting this issue event after upgraded to v2.4.0 which is the latest version.

**Comment by Mass812** [comment]
Was there any resolve for this issue?

**Comment by TharinduKetipe** [comment]
@oscb It's so disappointed to see that you have closed this issue without fixing it. Event the latest version 2.4.0 is giving this issue. We are having so many problems with upload new versions to Google play on our app. Recently our app has rejected by the google play by quoting the following issue. Can you guys take some actions to this or do I need to open another issue for this?
![Screenshot 2022-08-01 at 10 22 54](https://user-images.githubusercontent.com/8614553/182075272-7472af7f-1d37-4579-bcec-cc1694138912.png)

**Comment by oscb** [comment]
@Mass812 this issue was fixed in **v1.5.2** for people who cannot make the jump, and **v2+** (**recommended**). **Make sure you clean your gradle cache and make a clean build before submitting to Google,** we have known people for whose build keeps references of analytics-android after an upgrade.

@TharinduKetipe As you can see on my response above v2+ does not use analytics-android and v1.5.2 fixes your original Google Play issue about the AdvertisingId usage. You are sending a different error this time. We don't ask for `QUERY_ALL_PACKAGES` permission anywhere in this library. You should check your android-manifest file.

**Comment by TharinduKetipe** [comment]
@oscb We don't have QUERY_ALL_PACKAGES permission anywhere in our project manifest file. Since previous issue was specifically pointed segmentation library, I thought this was too with it. Do you mean if we downgraded our current version 2.4.0 to v1.5.2 will solve that issue? Because we still have above mentioned sdk isue for v2.4.0 as well.

**Comment by oscb** [comment]
@TharinduKetipe yes. V1.5.2 fixes your original issue too. Make sure you are making a clean build, again it is possible to have leftovers of native dependencies with react native when sending to Google. 
Also if you did the migration to v2 you will have to switch back your plugins to their v1 equivalents. The initialization code is slightly different between v1 and v2.

I don't know where this query_all_packages permission is coming from for your app but you should double check your dependencies, native libraries can add permissions to your manifest.

**Comment by TharinduKetipe** [comment]
@oscb I think it might be a gradle caching issue. I have done a clean build, seems like it still has all reference. I'll find a way to do some hard gradle cleanup. Thanks

**Comment by s23h** [comment]
Having this same issue with version 2.7.0 and tried clearing cache/clean build

**Comment by oscb** [comment]
@s23h can you share what was the error that you are seeing in the Google submission?

**Comment by TharinduKetipe** [comment]
My issue was gradle caching. Eventhough I have updated the library the old one was cached. Even gradle cache/clean build wasn't working for me. I removed package-lock.json and install all the dependencies from the beginning from npm install. That works for me

**Comment by s23h** [comment]
My issue was that I had expo-analytics installed. Once I uninstalled the
error was gone.

Best,
Salman
