### ISSUE TITLE
[2.19.2] Possible Unhandled Promise Rejection (id: 0): Error: Promise timed out

### ISSUE THREAD

**Issue by efstathiosntonas** [segmentio/analytics-react-native#954]
I get this on app start: 

```
Possible Unhandled Promise Rejection (id: 0):
Error: Promise timed out
Error: Promise timed out
```

and later on: 

```
Promise Rejection Handled (id: 0):
 WARN    This means you can ignore any previous messages of the form "Possible Unhandled Promise Rejection" with id 0.
```

* https://github.com/segmentio/analytics-react-native/blob/e079c71958d8f57cdc7bf4f1131bd2ce4d483284/packages/core/src/util.ts#L236

- `analytics-react-native` version: 2.19.2
- Integrations versions (if used):
- React Native version: 0.74.2
- iOS or Android or both? Both

**Steps to reproduce**

**Expected behavior**
don't know
**Actual behavior**
throws promise timeout

**Comment by efstathiosntonas** [comment]
It appears that this is happening only on 2.19.2, downgrading to 2.19.1 does not show the rejection any more.

**Comment by gitwilliam** [comment]
It may be unrelated, but I was getting the same error mention in the OP and also: `Queue timeout before completed restoration`. Downgrading to 2.19.1 resolved both of them.

**Comment by alanjcharles** [comment]
hi folks thanks for the report- will prioritize this and follow up asap.

**Comment by alanjcharles** [comment]
@efstathiosntonas @gitwilliam At present, the only PR I can find related to this issue is #943. From what I can tell in my investigation so far, these errors on app launch are expected and described in detail in that PR mentioned above. The change was introduced to prevent flushing before plugins (including SegmentDestination) are initialized. I can reproduce the warnings you are seeing but I am not experiencing any event loss. 

Please let me know if you are experiencing event loss or any other unintended/regressive behavior and we can go from there.

**Comment by jvgeee** [comment]
@alanjcharles No event loss, but I'm getting these errors every few seconds when running my app (not just at app launch). Please have them as opt-in through a config flag or something, it's clogging up my debug terminal!

<img width="620" alt="image" src="https://github.com/segmentio/analytics-react-native/assets/2121331/d2052258-7fd6-48e6-ad85-b1f3e1a2fac4">

**Comment by efstathiosntonas** [comment]
@alanjcharles same as @jvgeee, It’s clogging the terminal and it’s really annoying since our minds automatically tries to find out what is going on when we see a promise rejection happening 😂

**Comment by paulina-grunwald** [comment]
I have same problems. any solutions?

**Comment by engineeringcontractorstockpile** [comment]
We also have that here.

**Comment by dwxw** [comment]
Same here.

**Comment by ijhar8** [comment]
getting same error on 2.19.1 with sdk "expo": "50.0.19"

**Comment by AuroPick** [comment]
same warning on 2.19.1

**Comment by hvardhan-unth** [comment]
Addressed in #966

**Comment by thianphat** [comment]
> Addressed in #966

Getting this still

**Comment by bhandanyan-nomad** [comment]
"Error: Queue timeout before completed restoration" persists (version: 2.19.2)

**Comment by jvgeee** [comment]
@alanjcharles @hvardhan-unth This hasn't been fixed and is still present as of 2.19.5, please reopen.
